ballad_list = [
   ['Jumping Jack is quick and bold', 'With skill his story will unfold'],
   ['THE BALLAD OF JUMPING JACK', 'A daring explorer named Jack...'],
   ['Once found a peculiar track...'],
   ['There were dangers galore...'],
   ['Even holes in the floor...'],
   ['So he kept falling flat on', 'his back...'],
   ['Quite soon he got used to', 'the place...'],
   ['He could jump to escape from', 'the chase...'],
   ['But without careful thought...'],
   ['His leaps came to nought...'],
   ['And he left with a much', 'wider face...'],
   ['Things seemed just as bad as', 'could be...'],
   ['Hostile faces were all Jack', 'could see...'],
   ['He tried to stay calm...'],
   ['And to come to no harm...'],
   ['But more often got squashed', 'like a flea...'],
   ['By now Jack was in a', 'great flap...'],
   ['He felt like a rat in a trap...'],
   ['If only he`d guessed...'],
   ['That soon he could rest...'],
   ['After jumping the very', 'last gap.       - WELL DONE'],
]
