ballad_list = [
   'Jumping Jack is quick and bold\nWith skill his story will unfold',
   'THE BALLAD OF JUMPING JACK\nA daring explorer named Jack...',
   'Once found a peculiar track...',
   'There were dangers galore...',
   'Even holes in the floor...',
   'So he kept falling flat on\nhis back...',
   'Quite soon he got used to\nthe place...',
   'He could jump to escape from\nthe chase...',
   'But without careful thought...',
   'His leaps came to nought...',
   'And he left with a much\nwider face...',
   'Things seemed just as bad as\ncould be...',
   'Hostile faces were all Jack\ncould see...',
   'He tried to stay calm...',
   'And to come to no harm...',
   'But more often got squashed\nlike a flea...',
   'By now Jack was in a\ngreat flap...',
   'He felt like a rat in a trap...',
   'If only he`d guessed...',
   'That soon he could rest...',
   'After jumping the very\nlast gap.       - WELL DONE',
]
